DELETE http://localhost:3001/api/blogs/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1c2FuQHRlc3QuY29tIiwiaWQiOjEsImlhdCI6MTY5NDY3NjYwNn0.1xXsYTVyXQYsvxQsU1qzSdiSNo6Y3TcbBsv1WX9t0Ic