DELETE http://localhost:3001/api/blogs/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1c2FuQHRlc3QuY29tIiwiaWQiOjEsImlhdCI6MTY5NDYwMjUyM30.ONuARcAHwtJ6bFahvaMZQcJ40-rm1uFlgjCeXl1GGhU