POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0YTY4ZDI5ODc1NDMxNzdmNTAyY2E3OCIsImlhdCI6MTY4OTQ5NDk1MCwiZXhwIjoxNjg5NDk4NTUwfQ.xIrr2Pu8WegpYiHgTKikG3NIkjvrcmdqI0u2nr1qeP4

{
  "title": "Super cool post",
  "author": "Dusan and Tarn",
  "url": "itssupercoooool.com",
  "likes": 20,
  "blogs": 25,
  "userId": "64a2b64859710ab167b6b255"
}