POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Cat post",
  "author": "Dusanooo",
  "url": "catsarecool.com",
  "likes": 20,
  "blogs": 15,
  "userId": "64a2b64859710ab167b6b255"
}